// <auto-generated/>
using System;
using ApiData = System.Collections.Generic.Dictionary<string, System.Delegate>;

namespace VoxelCubemapApi.Api
{
    /// <summary>
    /// Defines the root API published by the session-level API manager.
    /// </summary>
    public sealed class ApiProvider
    {
        private readonly Func<long, ApiData> _getModificationTemplate;
        private readonly Func<Version> _getApiVersion;


        public ApiProvider(
            ApiData api)
        {
            if (api == null)
                throw new ArgumentNullException("api");

            _getModificationTemplate =
                GetRequired<Func<long, ApiData>>(
                    api,
                    "GetModificationTemplate");

            _getApiVersion =
                GetRequired<Func<Version>>(
                    api,
                    "GetApiVersion");
        }


        /// <summary>
        /// Creates a mutable modification template for the requested planet and
        /// returns its nested delegate API.
        /// </summary>
        public ModificationTemplate GetModificationTemplate(
            long entityId)
        {
            ApiData nestedApi =
                _getModificationTemplate(entityId);

            return nestedApi == null
                ? null
                : new ModificationTemplate(nestedApi);
        }


        /// <summary>
        /// Returns the version implemented by the server's root API.
        /// </summary>
        public Version GetApiVersion()
        {
            return _getApiVersion();
        }


        private static T GetRequired<T>(
            ApiData api,
            string id)
            where T : class
        {
            Delegate value;
            T result = api.TryGetValue(id, out value)
                ? value as T
                : null;

            if (result == null)
            {
                throw new InvalidOperationException("API mirror 'VoxelCubemapApi.Api.ApiProvider' is missing delegate '" + id + "'.");
            }

            return result;
        }
    }
}
