// <auto-generated/>
using System;
using ApiData = System.Collections.Generic.Dictionary<string, System.Delegate>;

namespace VoxelCubemapApi.Api
{
    /// <summary>
    /// Defines the root API published by the session-level API manager.
    /// </summary>
    public sealed class ApiProvider
    {
        private readonly Func<long, ApiData> _getModificationTemplate;
        private readonly Func<long, bool, ApiData> _getPlanetMetadata;
        private readonly Func<ApiData> _getNoiseProvider;
        private readonly Func<ApiData> _getWaterUtil;
        private readonly Func<ApiData> _getEnvironmentPresets;
        private readonly Func<Version> _getApiVersion;


        public ApiProvider(
            ApiData api)
        {
            if (api == null)
                throw new ArgumentNullException("api");

            _getModificationTemplate =
                GetRequired<Func<long, ApiData>>(
                    api,
                    "GetModificationTemplate");

            _getPlanetMetadata =
                GetRequired<Func<long, bool, ApiData>>(
                    api,
                    "GetPlanetMetadata");

            _getNoiseProvider =
                GetRequired<Func<ApiData>>(
                    api,
                    "GetNoiseProvider");

            _getWaterUtil =
                GetRequired<Func<ApiData>>(
                    api,
                    "GetWaterUtil");

            _getEnvironmentPresets =
                GetRequired<Func<ApiData>>(
                    api,
                    "GetEnvironmentPresets");

            _getApiVersion =
                GetRequired<Func<Version>>(
                    api,
                    "GetApiVersion");
        }


        /// <summary>
        /// Creates a mutable modification template for the requested planet and
        /// returns its nested delegate API.
        ///
        /// This template is thread-safe and can be used to modify the planet's procedural generation parameters.
        /// Recommended to use this method in a background <seealso cref="VRage.Game.ModAPI.IMyParallelTask"/>
        /// to avoid blocking the main game thread.
        /// </summary>
        public ModificationTemplate GetModificationTemplate(
            long entityId)
        {
            ApiData nestedApi =
                _getModificationTemplate(entityId);

            return nestedApi == null
                ? null
                : new ModificationTemplate(nestedApi);
        }


        /// <summary>
        /// Creates a read-only metadata for the requested planet, returns Null if no matching planet found
        /// returns its nested delegate API.
        /// </summary>
        public PlanetMetadataProvider GetPlanetMetadata(
            long entityId,
            bool includedVanilla)
        {
            ApiData nestedApi =
                _getPlanetMetadata(entityId, includedVanilla);

            return nestedApi == null
                ? null
                : new PlanetMetadataProvider(nestedApi);
        }


        /// <summary>
        /// Returns the root-level procedural noise provider.
        /// </summary>
        public NoiseProvider GetNoiseProvider()
        {
            ApiData nestedApi =
                _getNoiseProvider();

            return nestedApi == null
                ? null
                : new NoiseProvider(nestedApi);
        }


        /// <summary>
        /// Returns the root-level water/height conversion utility provider.
        /// </summary>
        public WaterUtil GetWaterUtil()
        {
            ApiData nestedApi =
                _getWaterUtil();

            return nestedApi == null
                ? null
                : new WaterUtil(nestedApi);
        }


        /// <summary>
        /// Returns the catalog of vegetation/environment presets discovered
        /// from all loaded compatible planet definitions.
        /// </summary>
        public EnvironmentPresetProvider GetEnvironmentPresets()
        {
            ApiData nestedApi =
                _getEnvironmentPresets();

            return nestedApi == null
                ? null
                : new EnvironmentPresetProvider(nestedApi);
        }


        /// <summary>
        /// Returns the version implemented by the server's root API.
        /// </summary>
        public Version GetApiVersion()
        {
            return _getApiVersion();
        }


        private static T GetRequired<T>(
            ApiData api,
            string id)
            where T : class
        {
            Delegate value;
            T result = api.TryGetValue(id, out value)
                ? value as T
                : null;

            if (result == null)
            {
                throw new InvalidOperationException("API mirror 'VoxelCubemapApi.Api.ApiProvider' is missing delegate '" + id + "'.");
            }

            return result;
        }
    }
}
