// <auto-generated/>
using System;
using ApiData = System.Collections.Generic.Dictionary<string, System.Delegate>;

namespace VoxelCubemapApi.Api
{
    /// <summary>
    /// Enumerates vegetation/environment presets supplied by loaded planet
    /// generator definitions without exposing engine definition objects.
    /// </summary>
    public sealed class EnvironmentPresetProvider
    {
        private readonly Func<string[]> _getPresetNames;
        private readonly Func<string, bool> _hasPreset;


        public EnvironmentPresetProvider(
            ApiData api)
        {
            if (api == null)
                throw new ArgumentNullException("api");

            _getPresetNames =
                GetRequired<Func<string[]>>(
                    api,
                    "GetPresetNames");

            _hasPreset =
                GetRequired<Func<string, bool>>(
                    api,
                    "HasPreset");
        }


        public string[] GetPresetNames()
        {
            return _getPresetNames();
        }


        public bool HasPreset(
            string presetName)
        {
            return _hasPreset(presetName);
        }


        private static T GetRequired<T>(
            ApiData api,
            string id)
            where T : class
        {
            Delegate value;
            T result = api.TryGetValue(id, out value)
                ? value as T
                : null;

            if (result == null)
            {
                throw new InvalidOperationException("API mirror 'VoxelCubemapApi.Api.EnvironmentPresetProvider' is missing delegate '" + id + "'.");
            }

            return result;
        }
    }
}
