// <auto-generated/>
using System;
using ApiData = System.Collections.Generic.Dictionary<string, System.Delegate>;

namespace VoxelCubemapApi.Api
{
    public sealed class FeatureTemplate
    {
        private readonly Action<int, int, double, double, int, int> _addCraterField;
        private readonly Action<int, int, double, double, int, int, float> _addCraterFieldBiased;


        public FeatureTemplate(
            ApiData api)
        {
            if (api == null)
                throw new ArgumentNullException("api");

            _addCraterField =
                GetRequired<Action<int, int, double, double, int, int>>(
                    api,
                    "AddCraterField");

            _addCraterFieldBiased =
                GetRequired<Action<int, int, double, double, int, int, float>>(
                    api,
                    "AddCraterFieldBiased");
        }


        /// <summary>
        /// Adds a compact deterministic crater field. Individual crater centers,
        /// radii and depths are regenerated from planetSeed + seedOffset + index
        /// when the feature pass executes; they are not serialized individually.
        /// Radius distribution is biased toward small impacts. Overlap is allowed.
        /// </summary>
        public void AddCraterField(
            int count,
            int seedOffset,
            double minimumRadiusDegrees,
            double maximumRadiusDegrees,
            int minimumDepth,
            int maximumDepth)
        {
            _addCraterField(count, seedOffset, minimumRadiusDegrees, maximumRadiusDegrees, minimumDepth, maximumDepth);
        }


        /// <summary>
        /// Adds a compact deterministic crater field with an explicit normalized
        /// target crater size. 0.5 is uniform, values below 0.5 increasingly favor
        /// smaller craters, and values above 0.5 increasingly favor larger craters.
        /// </summary>
        public void AddCraterFieldBiased(
            int count,
            int seedOffset,
            double minimumRadiusDegrees,
            double maximumRadiusDegrees,
            int minimumDepth,
            int maximumDepth,
            float targetSize)
        {
            _addCraterFieldBiased(count, seedOffset, minimumRadiusDegrees, maximumRadiusDegrees, minimumDepth, maximumDepth, targetSize);
        }


        private static T GetRequired<T>(
            ApiData api,
            string id)
            where T : class
        {
            Delegate value;
            T result = api.TryGetValue(id, out value)
                ? value as T
                : null;

            if (result == null)
            {
                throw new InvalidOperationException("API mirror 'VoxelCubemapApi.Api.FeatureTemplate' is missing delegate '" + id + "'.");
            }

            return result;
        }
    }
}
