// <auto-generated/>
using System;
using ApiData = System.Collections.Generic.Dictionary<string, System.Delegate>;

namespace VoxelCubemapApi.Api
{
    public sealed class FeatureTemplate
    {
        private readonly Action<int, int, double, double, int, int> _addCraterField;
        private readonly Action<int, int, double, double, int, int, float> _addCraterFieldBiased;
        private readonly Action<int, int, double, double, int, int> _addVolcanoField;
        private readonly Action<int, int, double, double, int, int, float> _addVolcanoFieldBiased;
        private readonly Action<int, int, double, double, double, double, int, int> _addRavineField;
        private readonly Action<int, int, double, double, double, double, int, int, float> _addRavineFieldBiased;
        private readonly Action<int, int, int, int, double, double, double, double, int, int, double> _addRiverField;


        public FeatureTemplate(
            ApiData api)
        {
            if (api == null)
                throw new ArgumentNullException("api");

            _addCraterField =
                GetRequired<Action<int, int, double, double, int, int>>(
                    api,
                    "AddCraterField");

            _addCraterFieldBiased =
                GetRequired<Action<int, int, double, double, int, int, float>>(
                    api,
                    "AddCraterFieldBiased");

            _addVolcanoField =
                GetRequired<Action<int, int, double, double, int, int>>(
                    api,
                    "AddVolcanoField");

            _addVolcanoFieldBiased =
                GetRequired<Action<int, int, double, double, int, int, float>>(
                    api,
                    "AddVolcanoFieldBiased");

            _addRavineField =
                GetRequired<Action<int, int, double, double, double, double, int, int>>(
                    api,
                    "AddRavineField");

            _addRavineFieldBiased =
                GetRequired<Action<int, int, double, double, double, double, int, int, float>>(
                    api,
                    "AddRavineFieldBiased");

            _addRiverField =
                GetRequired<Action<int, int, int, int, double, double, double, double, int, int, double>>(
                    api,
                    "AddRiverField");
        }


        /// <summary>
        /// Adds a deterministic crater field. Individual crater centers,
        /// radii and depths are regenerated from planetSeed + seedOffset + index
        /// when the feature pass executes; they are not serialized individually.
        /// Radius distribution is biased toward medium impacts. Overlap is allowed.
        /// </summary>
        public void AddCraterField(
            int count,
            int seedOffset,
            double minimumRadiusDegrees,
            double maximumRadiusDegrees,
            int minimumDepth,
            int maximumDepth)
        {
            _addCraterField(count, seedOffset, minimumRadiusDegrees, maximumRadiusDegrees, minimumDepth, maximumDepth);
        }


        /// <summary>
        /// Adds a compact deterministic crater field with an explicit normalized
        /// target crater size. 0.5 is uniform, values below 0.5 increasingly favor
        /// smaller craters, and values above 0.5 increasingly favor larger craters.
        /// </summary>
        public void AddCraterFieldBiased(
            int count,
            int seedOffset,
            double minimumRadiusDegrees,
            double maximumRadiusDegrees,
            int minimumDepth,
            int maximumDepth,
            float targetSize)
        {
            _addCraterFieldBiased(count, seedOffset, minimumRadiusDegrees, maximumRadiusDegrees, minimumDepth, maximumDepth, targetSize);
        }


        /// <summary>
        /// Adds a compact deterministic volcano field. Volcano centers, radii and
        /// heights are regenerated from planetSeed + seedOffset + index when the
        /// feature pass executes. The profile includes a summit caldera.
        /// </summary>
        public void AddVolcanoField(
            int count,
            int seedOffset,
            double minimumRadiusDegrees,
            double maximumRadiusDegrees,
            int minimumHeight,
            int maximumHeight)
        {
            _addVolcanoField(count, seedOffset, minimumRadiusDegrees, maximumRadiusDegrees, minimumHeight, maximumHeight);
        }


        /// <summary>
        /// Adds a deterministic volcano field with an explicit normalized target
        /// size. Values below 0.5 increasingly favor smaller volcanoes.
        /// </summary>
        public void AddVolcanoFieldBiased(
            int count,
            int seedOffset,
            double minimumRadiusDegrees,
            double maximumRadiusDegrees,
            int minimumHeight,
            int maximumHeight,
            float targetSize)
        {
            _addVolcanoFieldBiased(count, seedOffset, minimumRadiusDegrees, maximumRadiusDegrees, minimumHeight, maximumHeight, targetSize);
        }


        /// <summary>
        /// Adds a compact deterministic ravine field. Ravine paths are regenerated
        /// from planetSeed + seedOffset + index when the feature pass executes.
        /// </summary>
        public void AddRavineField(
            int count,
            int seedOffset,
            double minimumLengthDegrees,
            double maximumLengthDegrees,
            double minimumWidthDegrees,
            double maximumWidthDegrees,
            int minimumDepth,
            int maximumDepth)
        {
            _addRavineField(count, seedOffset, minimumLengthDegrees, maximumLengthDegrees, minimumWidthDegrees, maximumWidthDegrees, minimumDepth, maximumDepth);
        }


        /// <summary>
        /// Adds a deterministic ravine field with an explicit normalized target
        /// size. Values below 0.5 increasingly favor shorter/narrower ravines.
        /// </summary>
        public void AddRavineFieldBiased(
            int count,
            int seedOffset,
            double minimumLengthDegrees,
            double maximumLengthDegrees,
            double minimumWidthDegrees,
            double maximumWidthDegrees,
            int minimumDepth,
            int maximumDepth,
            float targetSize)
        {
            _addRavineFieldBiased(count, seedOffset, minimumLengthDegrees, maximumLengthDegrees, minimumWidthDegrees, maximumWidthDegrees, minimumDepth, maximumDepth, targetSize);
        }


        /// <summary>
        /// Adds deterministic sea-level river corridors. Each river chooses a seeded
        /// inland source, connects it to the nearest terrain sample at/below the fixed
        /// shoreline height, then carves a meandering spherical channel down to that
        /// water level. Planning uses a coarse six-face shoreline index and bounded
        /// source attempts;
        /// </summary>
        public void AddRiverField(
            int count,
            int seedOffset,
            int shorelineHeight,
            int minimumSourceHeightAboveShoreline,
            double minimumLengthDegrees,
            double maximumLengthDegrees,
            double minimumWidthDegrees,
            double maximumWidthDegrees,
            int minimumDepth,
            int maximumDepth,
            double shoulderWidthMultiplier)
        {
            _addRiverField(count, seedOffset, shorelineHeight, minimumSourceHeightAboveShoreline, minimumLengthDegrees, maximumLengthDegrees, minimumWidthDegrees, maximumWidthDegrees, minimumDepth, maximumDepth, shoulderWidthMultiplier);
        }


        private static T GetRequired<T>(
            ApiData api,
            string id)
            where T : class
        {
            Delegate value;
            T result = api.TryGetValue(id, out value)
                ? value as T
                : null;

            if (result == null)
            {
                throw new InvalidOperationException("API mirror 'VoxelCubemapApi.Api.FeatureTemplate' is missing delegate '" + id + "'.");
            }

            return result;
        }
    }
}
