// <auto-generated/>
using System;
using VRage.Game;
using ApiData = System.Collections.Generic.Dictionary<string, System.Delegate>;

namespace ProceduralCubemapApi.Api
{
    /// <summary>
    /// Server-owned mutable template exposed to another mod only through a
    /// dictionary of BCL delegates.
    /// </summary>
    public sealed class ModificationTemplate
    {
        private readonly Func<long> _getPlanetEntityId;
        private readonly Func<long> _getPlanetSeed;
        private readonly Action<string> _setGeneratorName;
        private readonly Action<string> _setPlanetName;
        private readonly Func<string, byte[][]> _loadPlanetPng;
        private readonly Func<string, int[]> _getPlanetPngSize;
        private readonly Func<string, int[]> _getPlanetPngInfo;
        private readonly Func<byte[]> _getUsedBiomes;
        private readonly Action<string, Action<int, int, byte[], byte[], byte[], byte[]>> _applyPlanetImage;
        private readonly Func<string, byte, float, bool> _addMaterial;
        private readonly Func<string, float, byte> _addMaterial2;
        private readonly Func<MyPlanetMaterialGroup, byte> _addComplexMaterial;
        private readonly Func<PlanetEnvironmentItemMapping[], int> _addEnvironmentItems;
        private readonly Action<string> _setEnvironmentDefinition;
        private readonly Action<string> _setEnvironmentPreset;
        private readonly Action<byte, int> _applyFractalNoise;
        private readonly Action<byte, byte> _replaceBiome;
        private readonly Action<byte, int> _applyBiomeFractalNoise;
        private readonly Action<string, int, bool, double, int, int, double, double, int, int, double, double, int, int> _applyBrush;
        private readonly Action<string, int, int, int, int, double, int, int, double, double, int, int, double, double, int, int> _applyNoiseBrush;
        private readonly Action<string, int, double, double, double, double, int, int, int, int, double, double, int, int> _applyRadialBrush;
        private readonly Func<ApiData> _addFeature;
        private readonly Func<byte, bool> _removeMaterial;
        private readonly Action<Action<bool, string>> _push;
        private readonly Func<Action> _pushNoCommit;
        private readonly Action<Action<bool, string>> _commitPendingPush;
        private readonly Action _close;


        public ModificationTemplate(
            ApiData api)
        {
            if (api == null)
                throw new ArgumentNullException("api");

            _getPlanetEntityId =
                GetRequired<Func<long>>(
                    api,
                    "GetPlanetEntityId");

            _getPlanetSeed =
                GetRequired<Func<long>>(
                    api,
                    "GetPlanetSeed");

            _setGeneratorName =
                GetRequired<Action<string>>(
                    api,
                    "SetGeneratorName");

            _setPlanetName =
                GetRequired<Action<string>>(
                    api,
                    "SetPlanetName");

            _loadPlanetPng =
                GetRequired<Func<string, byte[][]>>(
                    api,
                    "LoadPlanetPng");

            _getPlanetPngSize =
                GetRequired<Func<string, int[]>>(
                    api,
                    "GetPlanetPngSize");

            _getPlanetPngInfo =
                GetRequired<Func<string, int[]>>(
                    api,
                    "GetPlanetPngInfo");

            _getUsedBiomes =
                GetRequired<Func<byte[]>>(
                    api,
                    "GetUsedBiomes");

            _applyPlanetImage =
                GetRequired<Action<string, Action<int, int, byte[], byte[], byte[], byte[]>>>(
                    api,
                    "ApplyPlanetImage");

            _addMaterial =
                GetRequired<Func<string, byte, float, bool>>(
                    api,
                    "AddMaterial");

            _addMaterial2 =
                GetRequired<Func<string, float, byte>>(
                    api,
                    "AddMaterialSequential");

            _addComplexMaterial =
                GetRequired<Func<MyPlanetMaterialGroup, byte>>(
                    api,
                    "AddComplexMaterial");

            _addEnvironmentItems =
                GetRequired<Func<PlanetEnvironmentItemMapping[], int>>(
                    api,
                    "AddEnvironmentItems");

            _setEnvironmentDefinition =
                GetRequired<Action<string>>(
                    api,
                    "SetEnvironmentDefinition");

            _setEnvironmentPreset =
                GetRequired<Action<string>>(
                    api,
                    "SetEnvironmentPreset");

            _applyFractalNoise =
                GetRequired<Action<byte, int>>(
                    api,
                    "ApplyFractalNoise");

            _replaceBiome =
                GetRequired<Action<byte, byte>>(
                    api,
                    "ReplaceBiome");

            _applyBiomeFractalNoise =
                GetRequired<Action<byte, int>>(
                    api,
                    "ApplyBiomeFractalNoise");

            _applyBrush =
                GetRequired<Action<string, int, bool, double, int, int, double, double, int, int, double, double, int, int>>(
                    api,
                    "ApplyBrush");

            _applyNoiseBrush =
                GetRequired<Action<string, int, int, int, int, double, int, int, double, double, int, int, double, double, int, int>>(
                    api,
                    "ApplyNoiseBrush");

            _applyRadialBrush =
                GetRequired<Action<string, int, double, double, double, double, int, int, int, int, double, double, int, int>>(
                    api,
                    "ApplyRadialBrush");

            _addFeature =
                GetRequired<Func<ApiData>>(
                    api,
                    "AddFeature");

            _removeMaterial =
                GetRequired<Func<byte, bool>>(
                    api,
                    "RemoveMaterial");

            _push =
                GetRequired<Action<Action<bool, string>>>(
                    api,
                    "Push");

            _pushNoCommit =
                GetRequired<Func<Action>>(
                    api,
                    "PushNoCommit");

            _commitPendingPush =
                GetRequired<Action<Action<bool, string>>>(
                    api,
                    "CommitPendingPush");

            _close =
                GetRequired<Action>(
                    api,
                    "Close");
        }


        /// <summary>
        /// Returns the entity ID of the planet owned by this template.
        /// </summary>
        public long GetPlanetEntityId()
        {
            return _getPlanetEntityId();
        }


        /// <summary>
        /// Returns the seed of the planet owned by this template.
        /// </summary>
        public long GetPlanetSeed()
        {
            return _getPlanetSeed();
        }


        /// <summary>
        /// Selects the subtype name used for the runtime planet generator created
        /// by Push. The name must not already belong to a loaded definition.
        /// </summary>
        public void SetGeneratorName(
            string generatorName)
        {
            _setGeneratorName(generatorName);
        }


        /// <summary>
        /// Selects the visible and persistent storage name for the planet.
        /// The name is applied atomically when Push commits the template.
        /// </summary>
        public void SetPlanetName(
            string planetName)
        {
            _setPlanetName(planetName);
        }


        /// <summary>
        /// Loads one planet PNG as exactly four mutable byte planes. RGB images
        /// use RGBA order; 16-bit grayscale images use high/low sample bytes in
        /// planes zero and one.
        /// </summary>
        public byte[][] LoadPlanetPng(
            string faceFileName)
        {
            return _loadPlanetPng(faceFileName);
        }


        /// <summary>
        /// Returns the width and height of one planet PNG.
        /// </summary>
        public int[] GetPlanetPngSize(
            string faceFileName)
        {
            return _getPlanetPngSize(faceFileName);
        }


        /// <summary>
        /// Returns width, height, PNG bit depth, and PNG color type. For 16-bit
        /// grayscale maps, planes zero and one are the high/low sample bytes.
        /// </summary>
        public int[] GetPlanetPngInfo(
            string faceFileName)
        {
            return _getPlanetPngInfo(faceFileName);
        }


        /// <summary>
        /// Returns the sorted distinct biome IDs present in the green channel
        /// of the six material-map PNGs.
        /// </summary>
        public byte[] GetUsedBiomes()
        {
            return _getUsedBiomes();
        }


        /// <summary>
        /// Queues a transformation over the four mutable planes of a planet PNG.
        /// The transformation executes on the background Push worker.
        /// </summary>
        public void ApplyPlanetImage(
            string faceFileName,
            Action<int, int, byte[], byte[], byte[], byte[]> transform)
        {
            _applyPlanetImage(faceFileName, transform);
        }


        /// <summary>
        /// Adds a simple voxel material definition at the requested map value.
        /// The existing explicit-ID contract is preserved.
        /// </summary>
        public bool AddMaterial(
            string materialSubtype,
            byte mapValue,
            float maxDepth)
        {
            return _addMaterial(materialSubtype, mapValue, maxDepth);
        }


        /// <summary>
        /// Adds a simple voxel material definition using a server-allocated map
        /// value and returns that value. This is the preferred registration path
        /// when the caller does not require a specific byte ID.
        /// </summary>
        public byte AddMaterial(
            string materialSubtype,
            float maxDepth)
        {
            return _addMaterial2(materialSubtype, maxDepth);
        }


        /// <summary>
        /// Clones a complex material group and returns a map value unused by the
        /// source maps and template definitions.
        /// </summary>
        public byte AddComplexMaterial(
            MyPlanetMaterialGroup materialGroup)
        {
            return _addComplexMaterial(materialGroup);
        }


        /// <summary>
        /// Appends client-authored vegetation/environment mappings and returns
        /// the number added.
        /// </summary>
        public int AddEnvironmentItems(
            PlanetEnvironmentItemMapping[] mappings)
        {
            return _addEnvironmentItems(mappings);
        }


        /// <summary>
        /// Selects a caller-owned WorldEnvironmentDefinition through a normally
        /// loaded PlanetGeneratorDefinition carrier.
        /// </summary>
        public void SetEnvironmentDefinition(
            string carrierPlanetGeneratorSubtype)
        {
            _setEnvironmentDefinition(carrierPlanetGeneratorSubtype);
        }


        /// <summary>
        /// Selects and later remaps a vegetation/environment preset from the
        /// loaded planet definition library. The last explicit/preset setter
        /// wins.
        /// </summary>
        public void SetEnvironmentPreset(
            string presetName)
        {
            _setEnvironmentPreset(presetName);
        }


        /// <summary>
        /// Applies seamless planet-space fractal noise to the material channel.
        /// Selected pixels receive the requested map value during Push.
        /// </summary>
        public void ApplyFractalNoise(
            byte mapValue,
            int coveragePercent)
        {
            _applyFractalNoise(mapValue, coveragePercent);
        }


        /// <summary>
        /// Replaces every occurrence of one biome ID with another across all six
        /// material maps during Push.
        /// </summary>
        public void ReplaceBiome(
            byte sourceBiome,
            byte targetBiome)
        {
            _replaceBiome(sourceBiome, targetBiome);
        }


        /// <summary>
        /// Applies seamless planet-space fractal noise to the biome channel.
        /// Selected pixels receive the requested biome value during Push.
        /// </summary>
        public void ApplyBiomeFractalNoise(
            byte biomeValue,
            int coveragePercent)
        {
            _applyBiomeFractalNoise(biomeValue, coveragePercent);
        }


        /// <summary>
        /// Queues a filtered cubemap brush. The layer is Material, Biome, Ore,
        /// or Heightmap. Material/Biome/Ore fills use byte values; Heightmap
        /// uses an unsigned 16-bit sample. Altitude filters use that same
        /// unsigned 16-bit height sample and -1 disables either bound.
        /// Latitude is signed degrees. Biome/material filters use -1 for any.
        /// When procedural noise is enabled, only pixels whose normalized
        /// seamless cubemap noise falls inside the inclusive blend range are
        /// filled. Noise-specific parameters are ignored when useNoise is false.
        /// </summary>
        public void ApplyBrush(
            string layer,
            int fillValue,
            bool useNoise,
            double noiseFrequency,
            int noiseOctaves,
            int noiseSeedOffset,
            double blendNoiseMinimum,
            double blendNoiseMaximum,
            int minimumAltitude,
            int maximumAltitude,
            double minimumLatitude,
            double maximumLatitude,
            int biomeFilter,
            int materialFilter)
        {
            _applyBrush(layer, fillValue, useNoise, noiseFrequency, noiseOctaves, noiseSeedOffset, blendNoiseMinimum, blendNoiseMaximum, minimumAltitude, maximumAltitude, minimumLatitude, maximumLatitude, biomeFilter, materialFilter);
        }


        /// <summary>
        /// Queues a brush driven by one of the API-owned procedural noise
        /// generators. For Heightmap brushes the sampled normalized noise
        /// scales fillValue, then heightBlendMode selects Replace/Add/Subtract.
        /// Non-height layers retain normal replacement semantics and use the
        /// noise only for pixel selection.
        /// </summary>
        public void ApplyNoiseBrush(
            string layer,
            int fillValue,
            int noiseType,
            int heightBlendMode,
            NoiseSamplingQuality samplingQuality,
            double noiseFrequency,
            int noiseOctaves,
            int noiseSeedOffset,
            double blendNoiseMinimum,
            double blendNoiseMaximum,
            int minimumAltitude,
            int maximumAltitude,
            double minimumLatitude,
            double maximumLatitude,
            int biomeFilter,
            int materialFilter)
        {
            _applyNoiseBrush(layer, fillValue, noiseType, heightBlendMode, (int)samplingQuality, noiseFrequency, noiseOctaves, noiseSeedOffset, blendNoiseMinimum, blendNoiseMaximum, minimumAltitude, maximumAltitude, minimumLatitude, maximumLatitude, biomeFilter, materialFilter);
        }


        /// <summary>
        /// Queues a spherical radial field brush. Center coordinates are a planet-space
        /// direction and are normalized by the API. Radius is expressed in angular degrees.
        /// </summary>
        public void ApplyRadialBrush(
            string layer,
            int fillValue,
            double centerX,
            double centerY,
            double centerZ,
            double radiusDegrees,
            RadialFieldProfile radialProfile,
            int heightBlendMode,
            int minimumAltitude,
            int maximumAltitude,
            double minimumLatitude,
            double maximumLatitude,
            int biomeFilter,
            int materialFilter)
        {
            _applyRadialBrush(layer, fillValue, centerX, centerY, centerZ, radiusDegrees, (int)radialProfile, heightBlendMode, minimumAltitude, maximumAltitude, minimumLatitude, maximumLatitude, biomeFilter, materialFilter);
        }


        /// <summary>
        /// Adds one reusable procedural feature pass and returns its nested template.
        /// Feature generators are stored compactly and expanded only while baking.
        /// </summary>
        public FeatureTemplate AddFeature()
        {
            ApiData nestedApi =
                _addFeature();

            return nestedApi == null
                ? null
                : new FeatureTemplate(nestedApi);
        }


        /// <summary>
        /// Removes a material map value unless a default surface material uses it.
        /// </summary>
        public bool RemoveMaterial(
            byte mapValue)
        {
            return _removeMaterial(mapValue);
        }


        /// <summary>
        /// Commits this template asynchronously and invokes the completion callback.
        /// </summary>
        public void Push(
            Action<bool, string> callback)
        {
            _push(callback);
        }


        /// <summary>
        /// Freezes this template and returns the expensive, worker-safe portion
        /// of Push as an action suitable for IMyParallelTask.Do. Call
        /// CommitPendingPush on the simulation thread after the action
        /// has finished.
        /// </summary>
        public Action PushNoCommit()
        {
            return _pushNoCommit();
        }


        /// <summary>
        /// Commits a completed deferred Push on the simulation thread and
        /// invokes the callback before returning.
        /// </summary>
        public void CommitPendingPush(
            Action<bool, string> callback)
        {
            _commitPendingPush(callback);
        }


        /// <summary>
        /// Closes this template and releases its mutable server-side resources.
        /// </summary>
        public void Close()
        {
            _close();
        }


        private static T GetRequired<T>(
            ApiData api,
            string id)
            where T : class
        {
            Delegate value;
            T result = api.TryGetValue(id, out value)
                ? value as T
                : null;

            if (result == null)
            {
                throw new InvalidOperationException("API mirror 'ProceduralCubemapApi.Api.ModificationTemplate' is missing delegate '" + id + "'.");
            }

            return result;
        }
    }
}
