// <auto-generated/>
using System;
using ApiData = System.Collections.Generic.Dictionary<string, System.Delegate>;

namespace ProceduralCubemapApi.Api
{
    /// <summary>
    /// Root-level procedural noise service exposed through the intermod API.
    /// This keeps deterministic noise math and percentile sampling owned by
    /// the API server instead of duplicating it in client commands.
    /// </summary>
    public sealed class NoiseProvider
    {
        private readonly Func<long, double, int, int, int, double> _fractalBrownianMotionCoverage;


        public NoiseProvider(
            ApiData api)
        {
            if (api == null)
                throw new ArgumentNullException("api");

            _fractalBrownianMotionCoverage =
                GetRequired<Func<long, double, int, int, int, double>>(
                    api,
                    "FractalBrownianMotionCoverage");
        }


        /// <summary>
        /// Computes the brush blend threshold corresponding to the requested
        /// coverage for an arbitrary brush fBm profile. The result is in the
        /// same normalized [0,1] space used by ApplyBrush blend-noise limits.
        /// </summary>
        public double FractalBrownianMotionCoverage(
            long planetSeed,
            double frequency,
            int octaves,
            int seedOffset,
            int coveragePercent)
        {
            return _fractalBrownianMotionCoverage(planetSeed, frequency, octaves, seedOffset, coveragePercent);
        }


        private static T GetRequired<T>(
            ApiData api,
            string id)
            where T : class
        {
            Delegate value;
            T result = api.TryGetValue(id, out value)
                ? value as T
                : null;

            if (result == null)
            {
                throw new InvalidOperationException("API mirror 'ProceduralCubemapApi.Api.NoiseProvider' is missing delegate '" + id + "'.");
            }

            return result;
        }
    }
}
