// <auto-generated/>
namespace ProceduralCubemapApi.Api
{
    /// <summary>
    /// Controls how densely procedural noise is sampled across each cubemap
    /// face before brush application.
    /// </summary>
    public enum NoiseSamplingQuality
    {
        Low = 0,
        Medium = 1,
        High = 2,
        Direct = 3
    }
}
