// <auto-generated/>
using System;
using ApiData = System.Collections.Generic.Dictionary<string, System.Delegate>;

namespace ProceduralCubemapApi.Api
{
    /// <summary>
    /// Per-caller handle to a shared, immutable cubemap snapshot.
    /// </summary>
    public sealed class PlanetMetadataProvider
    {
        private readonly Func<Action<long, string>, bool> _subscribeRuntimePlanetChanged;
        private readonly Action<Action<long, string>> _unsubscribeRuntimePlanetChanged;
        private readonly Func<string, int[]> _getFaceSize;
        private readonly Func<string, ushort[]> _loadHeightFace;
        private readonly Func<string, byte[]> _loadMaterialFace;
        private readonly Func<string, byte[]> _loadBiomeFace;
        private readonly Action _close;


        public PlanetMetadataProvider(
            ApiData api)
        {
            if (api == null)
                throw new ArgumentNullException("api");

            _subscribeRuntimePlanetChanged =
                GetRequired<Func<Action<long, string>, bool>>(
                    api,
                    "SubscribeRuntimePlanetChanged");

            _unsubscribeRuntimePlanetChanged =
                GetRequired<Action<Action<long, string>>>(
                    api,
                    "UnsubscribeRuntimePlanetChanged");

            _getFaceSize =
                GetRequired<Func<string, int[]>>(
                    api,
                    "GetFaceSize");

            _loadHeightFace =
                GetRequired<Func<string, ushort[]>>(
                    api,
                    "LoadHeightFace");

            _loadMaterialFace =
                GetRequired<Func<string, byte[]>>(
                    api,
                    "LoadMaterialFace");

            _loadBiomeFace =
                GetRequired<Func<string, byte[]>>(
                    api,
                    "LoadBiomeFace");

            _close =
                GetRequired<Action>(
                    api,
                    "Close");
        }


        /// <summary>
        /// Subscribes this handle to replacement or unavailability of its
        /// planet. The callback receives the entity ID and new runtime subtype;
        /// a null subtype means the planet became unavailable.
        /// </summary>
        public bool SubscribeRuntimePlanetChanged(
            Action<long, string> callback)
        {
            return _subscribeRuntimePlanetChanged(callback);
        }


        /// <summary>
        /// Removes a callback previously registered by this handle.
        /// </summary>
        public void UnsubscribeRuntimePlanetChanged(
            Action<long, string> callback)
        {
            _unsubscribeRuntimePlanetChanged(callback);
        }


        /// <summary>
        /// Returns the width and height shared by the height, material, and
        /// biome arrays for one cubemap face.
        /// </summary>
        public int[] GetFaceSize(
            string face)
        {
            return _getFaceSize(face);
        }


        /// <summary>
        /// Loads one heightmap face as unsigned 16-bit samples.
        /// </summary>
        public ushort[] LoadHeightFace(
            string face)
        {
            return _loadHeightFace(face);
        }


        /// <summary>
        /// Loads the material (red) channel of one material-map face.
        /// </summary>
        public byte[] LoadMaterialFace(
            string face)
        {
            return _loadMaterialFace(face);
        }


        /// <summary>
        /// Loads the biome (green) channel of one material-map face.
        /// </summary>
        public byte[] LoadBiomeFace(
            string face)
        {
            return _loadBiomeFace(face);
        }


        /// <summary>
        /// Closes only this caller's handle and subscriptions. The shared
        /// snapshot remains alive while another handle still uses it.
        /// </summary>
        public void Close()
        {
            _close();
        }


        private static T GetRequired<T>(
            ApiData api,
            string id)
            where T : class
        {
            Delegate value;
            T result = api.TryGetValue(id, out value)
                ? value as T
                : null;

            if (result == null)
            {
                throw new InvalidOperationException("API mirror 'ProceduralCubemapApi.Api.PlanetMetadataProvider' is missing delegate '" + id + "'.");
            }

            return result;
        }
    }
}
