// <auto-generated/>
using System;
using Sandbox.ModAPI;
using ApiData = System.Collections.Generic.Dictionary<string, System.Delegate>;

namespace ProceduralCubemapApi.Api
{
    /// <summary>
    /// Performs a one-shot local mod-message request for the root API.
    /// </summary>
    public static class ProceduralCubemapApiClient
    {
        public const long REGISTRATION_CHANNEL = 6215908948244496385L;

        /// <summary>
        /// Returns the root API when the manager replies synchronously; otherwise null.
        /// </summary>
        public static ApiProvider TryGet(
            long replyChannel)
        {
            if (replyChannel == REGISTRATION_CHANNEL)
                return null;

            ApiProvider result = null;
            bool registered = false;

            Action<object> handler =
                delegate(object payload)
                {
                    ApiData api = payload as ApiData;

                    if (api != null)
                    {
                        result = new ApiProvider(api);
                    }
                };

            try
            {
                MyAPIGateway.Utilities.RegisterMessageHandler(
                    replyChannel,
                    handler);

                registered = true;

                MyAPIGateway.Utilities.SendModMessage(
                    REGISTRATION_CHANNEL,
                    replyChannel);
            }
            catch
            {
                result = null;
            }
            finally
            {
                if (registered)
                {
                    try
                    {
                        MyAPIGateway.Utilities.UnregisterMessageHandler(
                            replyChannel,
                            handler);
                    }
                    catch
                    {
                    }
                }
            }

            return result;
        }
    }
}
