// <auto-generated/>
using System;
using ApiData = System.Collections.Generic.Dictionary<string, System.Delegate>;

namespace VoxelCubemapApi.Api
{
    /// <summary>
    /// Root-level water/height conversion helper exposed through the intermod API.
    /// SE-Water stores its configured water level as a radius multiplier over
    /// MyPlanet.MinimumRadius. This provider converts that value to and from the
    /// planet cubemap heightmap's unsigned 16-bit altitude unit.
    /// </summary>
    public sealed class WaterUtil
    {
        private readonly Func<long, double, int> _waterRadiusToHeightmapUnit;
        private readonly Func<long, int, double> _heightmapUnitToWaterRadius;
        private readonly Func<long, double, int> _radiusMetersToHeightmapUnit;
        private readonly Func<long, int, double> _heightmapUnitToRadiusMeters;
        private readonly Func<long, double> _heightmapUnitsPerWaterRadiusUnit;
        private readonly Func<long, double> _metersPerHeightmapUnit;


        public WaterUtil(
            ApiData api)
        {
            if (api == null)
                throw new ArgumentNullException("api");

            _waterRadiusToHeightmapUnit =
                GetRequired<Func<long, double, int>>(
                    api,
                    "WaterRadiusToHeightmapUnit");

            _heightmapUnitToWaterRadius =
                GetRequired<Func<long, int, double>>(
                    api,
                    "HeightmapUnitToWaterRadius");

            _radiusMetersToHeightmapUnit =
                GetRequired<Func<long, double, int>>(
                    api,
                    "RadiusMetersToHeightmapUnit");

            _heightmapUnitToRadiusMeters =
                GetRequired<Func<long, int, double>>(
                    api,
                    "HeightmapUnitToRadiusMeters");

            _heightmapUnitsPerWaterRadiusUnit =
                GetRequired<Func<long, double>>(
                    api,
                    "HeightmapUnitsPerWaterRadiusUnit");

            _metersPerHeightmapUnit =
                GetRequired<Func<long, double>>(
                    api,
                    "MetersPerHeightmapUnit");
        }


        /// <summary>
        /// Converts an SE-Water radius multiplier to a cubemap heightmap value
        /// for the requested planet. A planet id of 0 targets the nearest planet
        /// to the local player, matching GetModificationTemplate(0).
        /// </summary>
        public int WaterRadiusToHeightmapUnit(
            long planetEntityId,
            double waterRadiusMultiplier)
        {
            return _waterRadiusToHeightmapUnit(planetEntityId, waterRadiusMultiplier);
        }


        /// <summary>
        /// Converts a cubemap heightmap value to the SE-Water radius multiplier
        /// for the requested planet. A planet id of 0 targets the nearest planet
        /// to the local player, matching GetModificationTemplate(0).
        /// </summary>
        public double HeightmapUnitToWaterRadius(
            long planetEntityId,
            int heightmapUnit)
        {
            return _heightmapUnitToWaterRadius(planetEntityId, heightmapUnit);
        }


        /// <summary>
        /// Converts an absolute radius in meters from planet center to a cubemap
        /// heightmap value for the requested planet.
        /// </summary>
        public int RadiusMetersToHeightmapUnit(
            long planetEntityId,
            double radiusMeters)
        {
            return _radiusMetersToHeightmapUnit(planetEntityId, radiusMeters);
        }


        /// <summary>
        /// Converts a cubemap heightmap value to an absolute radius in meters
        /// from planet center for the requested planet.
        /// </summary>
        public double HeightmapUnitToRadiusMeters(
            long planetEntityId,
            int heightmapUnit)
        {
            return _heightmapUnitToRadiusMeters(planetEntityId, heightmapUnit);
        }


        /// <summary>
        /// Returns the number of cubemap heightmap units represented by one
        /// SE-Water radius multiplier unit for the requested planet.
        /// </summary>
        public double HeightmapUnitsPerWaterRadiusUnit(
            long planetEntityId)
        {
            return _heightmapUnitsPerWaterRadiusUnit(planetEntityId);
        }


        /// <summary>
        /// Returns the number of meters represented by one cubemap heightmap
        /// unit for the requested planet.
        /// </summary>
        public double MetersPerHeightmapUnit(
            long planetEntityId)
        {
            return _metersPerHeightmapUnit(planetEntityId);
        }


        private static T GetRequired<T>(
            ApiData api,
            string id)
            where T : class
        {
            Delegate value;
            T result = api.TryGetValue(id, out value)
                ? value as T
                : null;

            if (result == null)
            {
                throw new InvalidOperationException("API mirror 'VoxelCubemapApi.Api.WaterUtil' is missing delegate '" + id + "'.");
            }

            return result;
        }
    }
}
